site_name: MMBbS Schulordnung

theme:
  name: null
  custom_dir: 'mmbbs_readthedocs/'
  favicon: bilder/favicon.png
  logo: bilder/logo.png
  # Config options for 'readthedocs' theme
  static_templates:
    - 404.html
  locale: de
  language: de
  include_search_page: true
  search_index_only: false
  highlightjs: true
  hljs_languages: []
  hljs_style: github
  analytics:
    gtag: null
    anonymize_ip: false
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  navigation_depth: 4
  titles_only: false
  sticky_navigation: true
  collapse_navigation: true

extra_css:
  - 'assets/css/extra.css'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

plugins:
  - include-markdown
  - search

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

use_directory_urls: false

repo_url: 

site_url: https://www.mmbbs.de

nav:
    - Schulordnung: 'index.md'
    - Anlage I: 'Anlage 1.md'
    - Anlage II: 'Anlage 2.md'
    - Anlage III: 'Anlage 3.md'
    - Anlage IV: 'Anlage 4.md'
    - Anlage V: 'Anlage 5.md'
    - Anlage VI: 'Anlage 6.md'
    - Anlage VII: 'Anlage 7.md'
    - Anlage VIII: 'Anlage 8.md'
    - Anlage IX: 'Anlage 9.md'
    - Anlage X: 'Anlage 10.md'
    - Anlage XI: 'Anlage 11.md'
    - Anlage XII: 'Anlage 12.md'
    - Changelog: 'changelog.md'